import React from 'react'
import { api, DriveTestingHistoryRow } from '../../api/client'
import { button, buttonRow, notice, section, sectionTitle, table, tableWrap, td, th } from './styles'

interface Props { rows: DriveTestingHistoryRow[]; onRefresh: () => void; onSelect: (id: string) => void; onCompare: (id: string) => void; onObservation: (id: string) => void; onError: (message: string) => void }

export default function ExperimentHistory({ rows, onRefresh, onSelect, onCompare, onObservation, onError }: Props) {
  const remove = async (id: string) => {
    if (!window.confirm('Delete this local IOSSim experiment? This does not delete third-party driving history.')) return
    try { await api.deleteDriveTestingExperiment(id); onRefresh() } catch (error: any) { onError(error.message) }
  }
  const openExport = (id: string, format: 'json' | 'csv') => window.open(api.driveTestingExportUrl(id, format), '_blank', 'noopener')
  return <section style={section}><div style={sectionTitle}>Experiment History</div><div style={{ ...notice('info'), marginBottom: 10 }}>Deleting a local IOSSim experiment does not delete third-party driving history.</div>
    {!rows.length ? <div style={notice('warning')}>No local experiment records.</div> : <div style={tableWrap}><table style={table}><thead><tr>{['Experiment ID', 'Date', 'Profile', 'Method', 'Requested', 'Emitted', 'Target', 'Calculated', 'Duration', 'Repeat', 'Failures', 'Observed result', 'QC', 'Notes', 'Actions'].map(label => <th style={th} key={label}>{label}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row.experiment_id}><td style={td}>{row.experiment_id}</td><td style={td}>{new Date(row.created_at).toLocaleString()}</td><td style={td}>{row.profile_name}</td><td style={td}>{row.method}</td><td style={td}>{(row.requested_distance_m / 1609.344).toFixed(2)} mi</td><td style={td}>{row.emitted_distance_m == null ? '-' : `${(row.emitted_distance_m / 1609.344).toFixed(2)} mi`}</td><td style={td}>See profile</td><td style={td}>{row.calculated_average_apparent_speed_mph == null ? '-' : `${row.calculated_average_apparent_speed_mph.toFixed(1)} mph`}</td><td style={td}>{row.actual_duration_s == null ? '-' : `${row.actual_duration_s.toFixed(1)} s`}</td><td style={td}>{row.repeat_number}</td><td style={td}>{row.write_failures}</td><td style={td}>{row.observed_result ?? 'Pending'}</td><td style={td}>{row.qc_status ?? 'INCOMPLETE'}</td><td style={td}>{row.notes}</td><td style={td}><div style={buttonRow}><button style={button()} onClick={() => onSelect(row.experiment_id)}>View</button><button style={button()} onClick={() => onSelect(row.experiment_id)}>Duplicate</button><button style={button()} onClick={() => onCompare(row.experiment_id)}>Compare</button><button style={button()} onClick={() => onObservation(row.experiment_id)}>Record Observation</button><button style={button()} onClick={() => openExport(row.experiment_id, 'json')}>Export JSON</button><button style={button()} onClick={() => openExport(row.experiment_id, 'csv')}>Export CSV</button><button style={button()} onClick={async () => { try { const report = await api.driveTestingReport(row.experiment_id); const windowRef = window.open('', '_blank'); if (windowRef) windowRef.document.body.innerText = report } catch (error: any) { onError(error.message) } }}>Generate Report</button><button style={button('danger')} onClick={() => remove(row.experiment_id)}>Delete Local Record</button></div></td></tr>)}</tbody></table></div>}
  </section>
}
